#########################################################################
# Main basil configuration. Basil will use the defaults shown for any
# values you don't specify.
#########################################################################

# Used to identify messages as to basil
#me: basil

# Plugin files are loaded from here
#plugins_directory: ./plugins

# Storage puts its data here
#pstore_file: ./basil.pstore

# Locking servers put their lock file here
#lock_file: /tmp/basil.lock

# When run as daemon, where to send our output
#log_file: tmp/basil.log

# When run as daemon, where to place our pid file
#pid_file: tmp/basil.pid

# Email will not be checked if not defined
#email:
  #interval: 30 # seconds
  #server:   imap.gmail.com
  #port:     993
  #username: X
  #password: X
  #inbox:    INBOX
  #verify:   true

# This may be required on OSX for HTTPS requests to work
#https_cert_file: /opt/local/share/curl/curl-ca-bundle.crt

#########################################################################
# Additional configuration specific to plugins. It is not guaranteed
# that plugins will work without specifying values for these.
#
# Note that you can add whatever keys you want here and access their
# values from your own plugins simply with value = Basil::Config.key
#########################################################################

jenkins:
  host:     jenkins.example.com
  port:     80
  user:     X
  password: X # Api key in newer versions
  broadcast_chat: "Name of chat to hear about broken builds (name, not topic)"

jira:
  host:     jira.example.com
  port:     443
  user:     X
  password: X

confluence:
  host:     confluence.example.com
  port:     443
  user:     X
  password: X

airbrake:
  account: some_name
  project: some_number    # https://some_name.airbrakeapp.com/<project>/errors
  token:   some_long_hash # available in airbrake admin settings

twitter:
  consumer_key:       xxx
  consumer_secret:    xxx
  oauth_token:        xxx
  oauth_token_secret: xxx
